'''
Each new term in the Fibonacci sequence is generated by 
adding the previous two terms. By starting with 1 and 2, 
the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose 
values do not exceed four million, find the sum of the 
even-valued terms.
'''
#1, 2, 3, 5, 8, 13, 21, 34, 55, 89
from time import time    

start_time = time()

soma = 0
y = 0
x = 1
while x <= 4000000:
    x = x + y
    y = x - y
    if x % 2 == 0 :
        soma = soma + x
    
print '002',soma, "in", time() - start_time, "seconds"